### ISSUE TITLE
Offset std::vector problem in addConstraintSegment function

### ISSUE THREAD

**Issue by lgspirit** [gcherchi/FastAndRobustMeshArrangements#18] opened 2023-06-07 06:52 UTC
Hi,
I get an STL verification warning when trying the "mesh_arrangement" demo by loading my cube_torus.stl file.

[cube_torus.zip](https://github.com/gcherchi/FastAndRobustMeshArrangements/files/11673411/cube_torus.zip)

![image](https://github.com/gcherchi/FastAndRobustMeshArrangements/assets/122286351/1176dcc1-00be-49e3-bd87-cc69ad65bf92)
![image](https://github.com/gcherchi/FastAndRobustMeshArrangements/assets/122286351/85698d9d-0dfe-4213-908a-43c58c058af6)

I hope this thread helps you.

Thank you.

**Comment by mlivesu** [comment] 2023-06-07 07:01
hi, I am not sure I understand your issue. I just tried to run the same "mesh_arrangement" demo on my laptop on your input mesh and I get the correct result (attached)

[output.obj.zip](https://github.com/gcherchi/FastAndRobustMeshArrangements/files/11673523/output.obj.zip)

**Comment by lgspirit** [comment] 2023-06-07 07:14
Thank you for taking a look at this issue.
The first source of my problem is similar to this thread : https://github.com/gcherchi/InteractiveAndRobustMeshBooleans/issues/19.
I follow the algorithm in the paper and I decide to directly try the "FastAndRobustMeshArrangements" project. But I get the same issue I described above.

**Comment by lgspirit** [comment] 2023-06-07 07:18
I am working on Windows 11 with Visual Studio 2022

**Comment by mlivesu** [comment] 2023-06-07 07:30
the only thing that comes to my mind is a different setting for the decimal separator that may fool the STL parser. I'll try to find a windows machine and investigate this further. I'll keep you posted

**Comment by mlivesu** [comment] 2023-06-07 08:24
So, a colleague tested it on windows and here is what we found out: if you compile in Release mode it should work just fine. If you compile in Debug mode, there is an issue with one of those three iterators going beyond the end of the vector and, depending on the warning level of the STL, this triggers an exception. We'll try to fix that to make it work also in Debug, but you should be able to obtain the desired result by just switching to Release.

**Comment by lgspirit** [comment] 2023-06-07 08:58
ah good news.
Thank you for your answer!

**Comment by mlivesu** [comment] 2023-06-08 06:50
I have just committed an alternative version of that loop that should make it work also in Debug mode under Windows.
Can you please sync your local copy of the repo and confirm that the issue is resolved also on your side?

thanks!

**Closed as completed** 2023-07-27 09:34 UTC

**Comment by lgspirit** [comment] 2023-10-18 15:31
Hi, thank you everything works now.
